/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ingresosgastos.gui;

import ingresosgastos.dto.Operacion;
import ingresosgastos.logica.LogicaNegocio;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alexis
 */
public class DialogoListado extends javax.swing.JDialog {

    /**
     * Creates new form DialogoListadoIngresos
     */
    public DialogoListado(java.awt.Frame parent, boolean modal, int tipoOperacion) {
        super(parent, modal);
        initComponents();

        this.inicializarTabla(tipoOperacion); // Iniciamos la tabla despues de cargar componentes

    }

    /**
     * Inicializar la tabla Método que crea las columnas usando un modelo propio
     */
    private void inicializarTabla(int tipoOperacion) {

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Fecha", "Concepto", "Importe"});
        jTableListadoGastos.setModel(dtm);

        // Cargamos los datos en la tabla
        // Creamos una lista con la lista de la logica de negocio y la recorremos
        ArrayList<Operacion> operaciones = LogicaNegocio.getOperaciones();
        for (Operacion operacion : operaciones) {

            if (operacion.getTipoOperacion() == tipoOperacion) {
                dtm.addRow(operacion.toArrayString());
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListadoGastos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableListadoGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListadoGastos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListadoGastos;
    // End of variables declaration//GEN-END:variables
}
